{
    "version": 2.1,
    "node-base": {
        "steps": [
            "checkout",
            {
                "run": "npm install"
            }
        ]
    },
    "jobs": {
        "test-v14": {
            "docker": [
                {
                    "image": "circleci/node:14"
                }
            ],
            "steps": [
                "checkout",
                {
                    "run": "npm install"
                }
            ]
        },
        "test-v15": {
            "docker": [
                {
                    "image": "circleci/node:15"
                }
            ],
            "steps": [
                "checkout",
                {
                    "run": "npm install"
                }
            ]
        },
        "test-v16": {
            "docker": [
                {
                    "image": "circleci/node:16"
                }
            ],
            "steps": [
                "checkout",
                {
                    "run": "npm install"
                }
            ]
        }
    },
    "workflows": {
        "build": {
            "jobs": [
                "test-v14",
                "test-v15",
                "test-v16"
            ]
        }
    }
}
